import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { SITE_DESC, SITE_TITLE } from '../config'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: SITE_TITLE ?? 'Create Next App',
  description: SITE_DESC ?? 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="zh-CN">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
